# Set the base image to Ubuntu
FROM node

# File Author / Maintainer
MAINTAINER Gabriel Malet

# Install Node.js and other dependencies
RUN apt-get update && \
	apt-get -y install git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PM2
RUN npm install -g pm2

# Define working directory
WORKDIR /src

# Expose port
EXPOSE 8080

# Run app with the dev conf (PM2 used in watchmode)
CMD pm2 start --no-daemon processes.dev.json