nginx:
    build: ./nginx
    links:
        - node-app:node-app
    ports:
        - "80:80"
        - "443:443"
node-app:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"